### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/GasGridModels.jl#33]
v0.1.0
@JuliaRegistrator register()

**Comment by ccoffrin** [comment]
v0.1.0
@JuliaRegistrator register()

**Comment by ccoffrin** [comment]
v0.1.1
@JuliaRegistrator register()

**Comment by ccoffrin** [comment]
v0.1.1
@JuliaRegistrator register()

**Comment by tasseff** [comment]
v0.2.0
@JuliaRegistrator register()

**Comment by tasseff** [comment]
v0.3.0
@JuliaRegistrator register()

**Comment by tasseff** [comment]
v0.4.0
@JuliaRegistrator register()

**Comment by ccoffrin** [comment]
v0.5.1
@JuliaRegistrator register()

**Comment by ccoffrin** [comment]
v0.6.0
@JuliaRegistrator register()

**Comment by ccoffrin** [comment]
v0.7.0
@JuliaRegistrator register()
