### ISSUE TITLE
Incompitable packages

### ISSUE THREAD

**Issue by nerlboost** [lanl-ansi/GasGridModels.jl#39]
Dear Sir,

Recently I installed the GasPowerModels package in Julia. Then I tried to add the Pavito solver. It was unsuccessful.  It seems that the JuMP versions compatible with Pavito are different from those with GasModels. Without the Pavito solver,  GasPowerModels cannot run. Could you please give me some advice on this issue?

The GasPowerModels is really a powerful tool to model the gas and power coupling scenarios. Many thanks for your sharing.

Sincerely yours,
Sean 
——————————————————————————

julia> Pkg.add("Pavito")
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package JuMP [4076af6c]:
 JuMP [4076af6c] log:
 ├─possible versions are: [0.18.3-0.18.6, 0.19.0-0.19.2, 0.20.0-0.20.1, 0.21.0-0.21.2] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.18.3-0.18.6, 0.19.0-0.19.2, 0.20.0-0.20.1, 0.21.0-0.21.2]
 ├─restricted by compatibility requirements with GasModels [5e113713] to versions: 0.19.1-0.19.2
 │ └─GasModels [5e113713] log:
 │   ├─possible versions are: [0.3.0, 0.3.2-0.3.5, 0.4.0-0.4.1, 0.5.0, 0.6.0] or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions [0.3.0, 0.3.2-0.3.5, 0.4.0-0.4.1, 0.5.0, 0.6.0]
 │   └─restricted by compatibility requirements with GasPowerModels [1fcaf345] to versions: 0.4.0-0.4.1
 │     └─GasPowerModels [1fcaf345] log:
 │       ├─possible versions are: 0.1.0-0.1.1 or uninstalled
 │       └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.1.1
 └─restricted by compatibility requirements with Pavito [cd433a01] to versions: 0.18.3-0.18.6 — no versions left
   └─Pavito [cd433a01] log:
     ├─possible versions are: [0.1.1-0.1.2, 0.2.0] or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions [0.1.1-0.1.2, 0.2.0]

**Comment by ccoffrin** [comment]
Hi Sean, the core issue here is that Pavito has not been updated to JuMP v0.19+, while most other solvers and related tools have been updated (including this one).  You can follow this issue for when Pavito will be available in JuMP v0.19.  https://github.com/JuliaOpt/Pavito.jl/issues/7

In the meantime the open source solver Juniper.jl should work.  We can also recomend Gurobi as a high performance solver for some classes of problems uses in GasPowerModels.

**Comment by nerlboost** [comment]
Many thanks.
