### ISSUE TITLE
objective function unification

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/GasGridModels.jl#53]
Consider unifying the objectives (and problem formulations) min_ne, min_opf, and min_ne_opf as a single function.  min_ne is min_ne_opf without opf and min_opf is min_ne_opf without ne.  With 0 cost provided as inputs, min_ne_opf could be used to model all three examples.  Is there value in modeling these three problems independently?

**Comment by tasseff** [comment]
I think this makes a lot of sense, and I would prefer to collapse these problem specifications into one. Then we would eventually have only three problem specifications: `gf`, `ne_opf`, and `mld`.
